config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations' }
 root to: "dashboards#index"
 
 resources :users do
   resources :exercises
 end
 
 resources :dashboards, only: [:index] do
   collection do
     post :search, to: 'dashboards#search'
   end
 end
 
 resources :friendships, only: [:show, :create, :destroy]
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :user

  alias_attribute :workout_details, :workout
  alias_attribute :activity_date, :workout_date

  validates :duration_in_min, numericality: { greater_than: 0.0 }
  validates :workout_details, presence: true
  validates :activity_date, presence: true
  validates :user_id, presence: true

  default_scope { where('workout_date > ?', 7.days.ago)
                  .order(workout_date: :desc) }

end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :exercises  
  has_many :friendships
  has_many :friends, through: :friendships, class_name: "User"
  
  validates :first_name, presence: true
  validates :last_name, presence: true
  
  def full_name
    "#{first_name} #{last_name}"
  end
  
  def self.search_by_name(name)
    names_array = name.split(' ')

    if names_array.size == 1
      where('first_name LIKE ? or last_name LIKE ?',
        "%#{names_array[0]}%", "%#{names_array[0]}%").order(:first_name)
    else
      where('first_name LIKE ? or first_name LIKE ? or last_name LIKE ?
        or last_name LIKE ?', "%#{names_array[0]}%",
        "%#{names_array[1]}%", "%#{names_array[0]}%",
        "%#{names_array[1]}%").order(:first_name)
    end
  end
  
  def follows_or_same?(new_friend)
    friendships.map(&:friend).include?(new_friend) || self == new_friend
  end
  
  def current_friendship(friend)
    friendships.where(friend: friend).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
    
  def index
    @athletes = User.paginate :page => params[:page], :per_page => 10
  end
  
  def search
    @athletes = User.search_by_name(params[:search_name]).paginate :page => params[:page]
  end
    
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]
  
  def index
    @exercises = current_user.exercises
    @friends = current_user.friends
  end
  
  def show
  end
  
  def new
    @exercise = current_user.exercises.new
  end
    
  def create
    @exercise = current_user.exercises.new(exercise_params)
    
    if @exercise.save
      flash[:notice] = "Exercise has been created"
      redirect_to [current_user, @exercise]
    else
      flash.now[:alert] = "Exercise has not been created"
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @exercise.update(exercise_params)
      flash[:notice] = 'Exercise has been updated'
      redirect_to [current_user, @exercise]
    else
      flash[:alert] = 'Exercise has not been updated'
      redirect_to [current_user, @exercise]
    end
  end
  
  def destroy
    @exercise.destroy
    flash[:danger] = 'Exercise has been deleted'
    redirect_to user_exercises_path(current_user)
  end
  
  private
   
  def set_exercise
    @exercise = current_user.exercises.find(params[:id])
  end
  
  def exercise_params 
    params.require(:exercise).permit(:duration_in_min, :workout, :workout_date, :user_id)
  end
  
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @friend = Friendship.find(params[:id]).friend
    @exercises = @friend.exercises
  end
  
  def create
    friend = User.find(params[:friend_id])
    params[:user_id] = current_user.id
    
    Friendship.create(friendship_params) unless current_user.follows_or_same?(friend)
    # Friendship.create(friendship_params.merge!(friend_id: params[:friend_id], 
    #   user_id: current_user.id)) unless current_user.follows_or_same?(friend)
    redirect_to root_path
  end
  
  def destroy
    @friendship = Friendship.find(params[:id])
    friendname = @friendship.friend.full_name
    
    if @friendship.destroy
      flash[:notice] = "#{friendname} unfollowed."
    else
      flash.now[:alert] = "#{friendname} could not be unfollowed."
    end
    redirect_to user_exercises_path(current_user)
  end
  
  private
  
  def friendship_params
    params.permit(:friend_id, :user_id)
  end
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  private
  
  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
  
  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/index.html.erb
<div class="jumbotron">
  <h1>Workout Lounge!</h1>
    
  <p>Show off your workout to your friends and family</p>
</div>

<div class="card" style="width: 48rem;">
  <div class="card-header">
    <h3>List of Members</h3>
  </div>
  <div class="pagination justify-content-center apple_pagination">
    <%= will_paginate @athletes %>
  </div>
  <ul class="list-group list-group-flush">
    <% @athletes.each do |athlete| %>
      <li class="list-group-item">
        <%= athlete.full_name %>
        <% if current_user %>
          <%= link_to "Follow", friendships_path(friend_id: athlete.id), method: :post, 
             class: "badge badge-info float-right" unless current_user.follows_or_same?(athlete) %>
        <% end %>
      </li>
    <% end %>
  </ul>
  <div class="pagination justify-content-center apple_pagination">
    <%= will_paginate @athletes %>
  </div>
</div>
<div class="pagination justify-content-center apple_pagination">
    <%= will_paginate @athletes %>
</div>

app/views/dashboards/search.html.erb
<div class="card" style="width: 28rem;">
  <div class="card-header">
    <h3>Results of Search</h3>
  </div>
  <div class="pagination justify-content-center apple_pagination">
    <%= will_paginate @athletes %>
  </div>
  <ul class="list-group list-group-flush">
    <% @athletes.each do |athlete| %>
      <li class="list-group-item"><%= athlete.full_name %></li>
    <% end %>
  </ul>
</div>
<div class="pagination justify-content-center apple_pagination">
    <%= will_paginate @athletes %>
</div>

app/views/exercises/_form.html.erb
<div class='container'>
  <div class='row justify-content-start'>
     <div class='w-100'>
      <%= form_for([current_user, @exercise], :html => {class: 'form-group', role: 'form' }) do |f| %>
        <% if @exercise.errors.any? %>
          <div class="card card-danger col-md-offset-1" id="error_explanation">
            <div class="cardl-heading">
              <h2 class="card-title">
                <%= pluralize(@exercise.errors.count, "error") %>
                prohibited this exercise from being saved:
              </h2>
              
              <div class="panel-body">
                <ul>
                  <% @exercise.errors.full_messages.each do |msg| %>
                  <li>
                    <%= msg %>
                  </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        <% end %>
        
      <div class='form-group row'>
        <div class='form-control-label col-2'>
          <%= f.label :duration_in_min, "Duration (min)" %>
        </div>
        <div class='col-10'>
          <%= f.number_field :duration_in_min, class: 'form-control' %>
        </div>
      </div>
      <div class='form-group row'>
        <div class='form-control-label col-2'>
          <%= f.label :workout, "Workout Details" %>
        </div>
        <div class='col-10'>
          <%= f.text_area :workout, rows: 10, class: 'form-control' %>
        </div>
      </div>
       <div class='form-group row'>
        <div class='form-control-label col-2'>
          <%= f.label :workout_date, "Activity Date" %>
        </div>
        <div class='col-10'>
          <%= f.text_area :workout_date, class: 'form-control' %>
        </div>
      </div>
      <div class='form-group'>
        <div class='col-10 offset-2'>
            <%= f.submit class: 'btn btn-primary btn-sm special-btn' %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/exercises/edit.html.erb
<h1 class="text-center">
  Editing Exercise for <%= current_user.full_name %>
</h1>

<%= render 'form' %>

<div class="row">
  <div class="col-12">
    <div class="col-10 offset-2">
      <%= link_to "Back", user_exercises_path(current_user), 
          class: "badge badge-dark link", id: "new-exer-btn" %>
    </div>
  </div>
</div>

app/views/exercises/index.html.erb
<div class="col-8 col-12">
    <% unless @exercises.empty? %>
    <h1>List of Exercises</h1>
    
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Duration (min)</th>
                <th>Workout Details</th>
                <th>Activity Date</th>
                <th colspan="3"></th>
            </tr>
        </thead>
        <tbody>
            <% @exercises.each do |exercise| %>
            <tr>
                <td><%= exercise.duration_in_min %></td>
                <td><%= truncate(exercise.workout, length: 100) %></td>
                <td><%= exercise.workout_date %></td>
                <td><%= link_to "Show", [current_user, exercise],
                                    class: "badge badge-info" %></td>
                <td><%= link_to "Edit", [:edit, current_user, exercise],
                                         class: "badge badge-warning"%></td>
                <td><%= link_to "Destroy", [current_user, exercise], method: :delete,
                                         data: { confirm: "Are you sure?" },
                                         class: "badge badge-danger" %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
    <br>
    <% else %>
    <div class="alert alert-danger message-font text-center" role="alert">
        No Workouts Yet
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
           </button>
    </div>
    <br>
    <% end %>
    <%= link_to "New Workout", new_user_exercise_path(current_user), 
                               class: "badge badge-info link" %>
    <%= content_tag :div, "", id: "chart", data: { workouts: @exercises } %>
</div>

<div class="col-4 col-12">
    <h3 class="text-center">My Friends</h3>
    
    <% @friends.each do |friend| %>
        <div class="col-offset-3 col-6 friend_name">
            <%= link_to friend.full_name, friendship_path(current_user.current_friendship(friend)) %>
        </div>
        
        <div class="col-3">
            <div class="btn-unfollow">
                <%= link_to "Unfollow", friendship_path(current_user.current_friendship(friend)),
                    method: :delete, data: { confirm: "Are you sure?" },
                    class: "badge badge-info link" %>
            </div>
        </div>
    <% end %>
</div>

app/views/exercises/new.html.erb
<h1 class="text-center">New Exercise for <%= current_user.full_name %></h1>

<%= render 'form' %>

<div class="row">
  <div class="col-12">
    <div class="col-10 offset-2">
      <%= link_to "Back", user_exercises_path(current_user), 
          class: "badge badge-dark link", id: "new-exer-btn" %>
    </div>
  </div>
</div>

app/views/exercises/show.html.erb
<div class="col-12 col-10 col-offset-1">
  <div>
    <h2 class="show-header">Showing <%= "#{@exercise.user.full_name}'s Workout Details" %></h2>
  </div>
  <div class="col-12 col-10 card member">
    <div class="col-4">
      <strong>Duration (min):</strong>
    </div>
    <div class="col-8 text-right">
      <%= @exercise.duration_in_min %>
    </div>
  </div>
  <div class="col-12 col-10 card member">
    <div class="col-4l">
      <strong>Workout Details:</strong>
    </div>
    <div class="col-8 text-right">
      <%= truncate(@exercise.workout, length: 50) %>
    </div>
  </div>
  <div class="col-12 col-10 card member">
    <div class="col-4">
      <strong>Activity Date:</strong>
    </div>
    <div class= "col-8 text-right">
      <%= @exercise.workout_date %>
    </div>
  </div>
  <br>
  <div class="row">
  <div class="col-12">
    <div class="col-10 offset-2">
      <%= link_to "Back", user_exercises_path(current_user), 
          class: "badge badge-dark link", id: "new-exer-btn" %>
    </div>
  </div>
</div>
</div>

app/views/friendships/show.html.erb
<div class="col-8">
  <p id="notice"><%= notice %></p>
  
  <h1><%= @friend.full_name %>'s Exercises</h1>
  
  <table clss="table table-striped">
    <thead>
      <tr>
        <th>Duration (min)</th>
        <th>Distance</th>
        <th>Activity Date</th>
      </tr>
    </thead>
    
    <tbody>
      <% @exercises.each do |exercise| %>
        <tr>
          <td><%= exercise.duration_in_min %></td>
          <td><%= truncate(exercise.workout, length: 100) %></td>
          <td><%= exercise.workout_date %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
    <br>
    
    <%= content_tag :div, "", id: "chart", data: {workout: @exercises} %>
    
    <br>
    
    <%= link_to "Back", user_exercises_path(current_user),
        class: "badge badge-info link" %>
      
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navigation' %>
    <%= render 'shared/error_messages' %>
    
    <div class="container">
      <%= yield %>
    </div>
    
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<div class="container">    
  <div class="row">
    <div class="col-12 mr-5">
      <% flash.each do |key, message| %>
        <div class="text-center alert alert-<%= key == 'notice' ? 'success' : 'danger' %>">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
           </button>
           <%= message %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="mt-4 fixed-bottom">
    <div class="container-fluid py-3">
      <div class="row">
          <div class="col-8">
            <small>Workout App <em>by Rhonda Tinkham &copy;2017</em></small>
          </div>
          <div class="col-4 text-right small align-self-end">
            <%= link_to 'About', '#' %>
          </div>
      </div>
    </div>
</footer>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light navbar-custom justify-content-start">
  <%= link_to 'Athletes Den', root_path, class: 'navar-brand pl-5 d-flex mr-auto', id: 'logo' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      
      <li class="nav-item">
         <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
    </ul>
    
    <%= form_tag(search_dashboards_path,
                 class: "form-inline my-2 my-lg-0",
                 role: "search") do %>
        <div class="form-group">
          <%= text_field_tag :search_name, nil, placeholder: "Search for friends",
              class: "form-control mr-sm-2" %>
          <%= submit_tag "Search", class: "btn btn-outline-default my-2 my-sm-0" %>
        </div>
    <% end %>
  
    <ul class="navbar-nav ml-auto w-75 justify-content-end">
      <% unless user_signed_in? %>
        <li class="nav-item">
           <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
           <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
        </li>
      <% else %>
         <li class="nav-item">
           <%= link_to "My Lounge", user_exercises_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item ">
           <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <li class="nav-item ">
           <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
        </li>
          <ul class="navbar-text">
            Signed in as <%= "#{current_user.email}" %>
          </ul>
      <% end %>
      
      
      
      <!--<li class="nav-item dropdown">-->
      <!--  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
      <!--    Dropdown-->
      <!--  </a>-->
      <!--  <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
      <!--    <a class="dropdown-item" href="#">Action</a>-->
      <!--    <a class="dropdown-item" href="#">Another action</a>-->
      <!--    <div class="dropdown-divider"></div>-->
      <!--    <a class="dropdown-item" href="#">Something else here</a>-->
      <!--  </div>-->
      <!--</li>-->
    </ul>
    <!--<form class="form-inline my-2 my-lg-0">-->
    <!--  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
      <!--<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
    <!--</form>-->
  </div>
</nav>